##
# RnDAO Analyzer
#
# @author Simon Sekavčnik
# @version 0.1

load:
				pip install -e .

install:
				pip install .

reload:
				pip uninstall rndao_analyzer
				pip install -e

unload:
				pip uninstall rndao_analyzer

# end
